// <auto-generated />
using System;
using CreatorApplication.Data.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreatorApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221115161551_InitialSetup")]
    partial class InitialSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("IngredientListId")
                        .HasColumnType("int");

                    b.Property<string>("IngredientName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientListId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.IngredientList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IngredientLists");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IngredientListId")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientsId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.RecipeReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeReviews");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Ingredient", b =>
                {
                    b.HasOne("CreatorApplication.Data.DataModels.IngredientList", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientListId");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Recipe", b =>
                {
                    b.HasOne("CreatorApplication.Data.DataModels.IngredientList", "Ingredients")
                        .WithMany()
                        .HasForeignKey("IngredientsId");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.RecipeReview", b =>
                {
                    b.HasOne("CreatorApplication.Data.DataModels.Recipe", null)
                        .WithMany("Reviews")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.IngredientList", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Recipe", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
