// <auto-generated />
using CreatorApplication.Data.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreatorApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("IngredientName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.IngredientsList", b =>
                {
                    b.Property<int>("RecipeIngredientsListId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("RecipeIngredientsListId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientsLists");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeIngredientsListId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeIngredientsListId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.RecipeIngredientsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("RecipeIngredientsLists");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.RecipeReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecipeReviews");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.IngredientsList", b =>
                {
                    b.HasOne("CreatorApplication.Data.DataModels.Ingredient", "Ingredient")
                        .WithMany("IngredientsList")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreatorApplication.Data.DataModels.RecipeIngredientsList", "RecipeIngredientsList")
                        .WithMany("IngredientsList")
                        .HasForeignKey("RecipeIngredientsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("RecipeIngredientsList");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Recipe", b =>
                {
                    b.HasOne("CreatorApplication.Data.DataModels.RecipeIngredientsList", "RecipeIngredients")
                        .WithOne()
                        .HasForeignKey("CreatorApplication.Data.DataModels.Recipe", "RecipeIngredientsListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.Ingredient", b =>
                {
                    b.Navigation("IngredientsList");
                });

            modelBuilder.Entity("CreatorApplication.Data.DataModels.RecipeIngredientsList", b =>
                {
                    b.Navigation("IngredientsList");
                });
#pragma warning restore 612, 618
        }
    }
}
